# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json
default_install_hook_types = ["pre-push"]

[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files" },
  { id = "end-of-file-fixer" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "mixed-line-ending" },
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.10.3"
hooks = [
  { id = "uv-lock" }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.1"
hooks = [
  { id = "ruff-check", args = ["--fix"] },
  { id = "ruff-format" }
]
